### ISSUE TITLE
Android or iOS scanners that work with this

### ISSUE THREAD

**Issue by yehudahkay** [CarlRaymond/jquery.cardswipe#23] opened 2017-07-19 18:11 UTC
Hi,

Do you know if any Android or iOS scanners will generate the proper output to be used this way?

Thank you

**Comment by treed593** [comment] 2017-07-20 16:41
Duplicate of #13

**Comment by Android-Geek5** [comment] 2017-08-10 07:16
Hi, 

I have  Magtek- 1. uDynamo 2. eDynamo 3. Magtek Bullet.

Can you please let me know that is there any possiblity to connect with these devices from browers of IOS and Android like chrome, Safari etc. I am working on it from 2-4 days but not find any solution to get connected with them. I have connected the android one with android SDK but i want to connect with these devices via browsers.

Thank you.

**Comment by CarlRaymond** [comment] 2017-08-10 18:25
I'm afraid I don't have a solution for that.  The plugin is designed for card readers that emulate keyboards, rather than use their own SDK. If that's what your readers do, then it's just like adding an external USB keyboard to the phone or tablet. If you can get a keyboard to work with the browser, the card reader should, too -- if it's a keyboard emulator.

In another thread, bflieshman has a reader working with iOS: https://github.com/CarlRaymond/jquery.cardswipe/issues/13#issuecomment-191996504

**Closed** 2018-03-15 03:10 UTC
